# Application config
rere:

  # Base url with schema and no trailing slash.
  baseurl: ${RERE_BASEURL:https://example.com}

  # Directory where replic content is stored
  content.root: ${RERE_CONTENT_ROOT:}

  # Config for the authentication
  auth:

    # Refresh-token expiration in millis
    refresh.expiration: ${RERE_AUTH_REFRESH_EXP:2592000000}

    # Email-token expiration in millis
    email.expiration: ${RERE_EMAIL_EXP:900000}

    # Config for the access-tokens
    access:

      # Access-token expiration duration in millis
      expiration: ${RERE_AUTH_ACCESS_EXP:900000}

      # Private key for signing JWT's
      secret: ${RERE_AUTH_ACCESS_SECRET:d2cf0591-a08d-4547-8cec-363daee402b0}

  # Config for the email messaging
  mail:

    # Username for authenticating to the smtp server
    username: ${RERE_MAIL_USERNAME:user@example.com}

    # Password for authenticating to the smtp server
    password: ${RERE_MAIL_PASSWORD:examplepassword}

    # Host of the smtp server
    smtpHost: ${RERE_MAIL_HOST:smtp.example.com}

    # Port of the smtp server
    smtpPort: ${RERE_MAIL_PORT:465}

    # Whether to use ssl encryption
    ssl: ${RERE_MAIL_SSL:true}

  # Config about the admin account
  admin:

    # Username of the admin account
    username: ${RERE_ADMIN_USERNAME:root}

    # Email of the admin account
    email: ${RERE_ADMIN_EMAIL:root@example.com}

    # Password to the admin account
    password: ${RERE_ADMIN_PASSWORD:root}

# Spring config
spring:

  # Datasource config:
  datasource:

    # Database username
    username: ${RERE_DB_USERNAME}

    # Database password
    password: ${RERE_DB_PASSWORD}

    # Database url
    url: ${RERE_DB_URL}

    # Driver class of the database
    driver-class-name: org.postgresql.Driver

  # SQl dialect of database implementation
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # How hibernate should react to schema differences. We want to update the schema.
  jpa.hibernate.ddl-auto: update

  profiles.active: ${RERE_SPRING_PROFILES:default}