# Logging level for spring security
logging.level.org.springframework.security: DEBUG

# Logging level for hibernate validation
log4j.logger.org.hibernate.validator: debug

# Exposes all actuator endpoints
management.endpoints.web.exposure.include: "*"